version: '3'
services:


  php:
    build:
      context: ./images
      dockerfile: php.docker
    container_name: php
    depends_on:
      - mysql
    restart: always
    volumes:
      - '../src:/code'
    environment:
      DB_HOST: "mysql"
      DB_PORT: 3306
      APPLICATION_USER: "${APPLICATION_USER}"
      APPLICATION_PASSWORD: "${APPLICATION_PASSWORD}"
      ADMIN_USER: "${ADMIN_USER}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"

  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
        - 3306
    environment:
        MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
        - "./data/db:/var/lib/mysql"
        - "./config/mysql/my.cnf:/etc/mysql/conf.d/ssl.cnf"
        - "./config/mysql/certs:/etc/ssl/mysql"