version: '3'
services:


  php:
    build:
      context: ./images
      dockerfile: php.docker
    container_name: php
    depends_on:
      - mysql
    restart: always
    volumes:
      - '../src:/code'
    environment:
      DB_HOST: "mysql"
      DB_DATABASE: "${MYSQL_DATABASE}"
      DB_PORT: 3306

  mysql:
    build:
        context: ./images
        dockerfile: mysql.docker
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
        - 3306
    environment:
        MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
        MYSQL_DATABASE: "${MYSQL_DATABASE}"
        MYSQL_USER: "${MYSQL_USER}"
        MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
        - "./data/db:/var/lib/mysql"
        - "./config/mysql/my.cnf:/etc/mysql/conf.d/ssl.cnf"